config/routes.rb
Rails.application.routes.draw do
  mount Maestrano::Connector::Rails::Engine, at: '/'

  root 'home#index'
  get 'home/index' => 'home#index'
  get 'home/redirect_to_external' => 'home#redirect_to_external'
  get 'home/index' => 'home#index'
  put 'home/update' => 'home#update'
  post 'home/synchronize' => 'home#synchronize'

  get 'synchronizations/index' => 'synchronizations#index'
  get 'shared_entities/index' => 'shared_entities#index'

  match 'auth/:provider/request', to: 'oauth#request_omniauth', via: [:get, :post]
  match 'auth/:provider/callback', to: 'oauth#create_omniauth', via: [:get, :post]
  match 'signout_omniauth', to: 'oauth#destroy_omniauth', as: 'signout_omniauth', via: [:get, :post]

  # Sidekiq Admin
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/synchronizations_controller.rb
class SynchronizationsController < ApplicationController
  def index
    if current_organization
      @synchronizations = Maestrano::Connector::Rails::Synchronization.where(organization_id: current_organization.id).order(updated_at: :desc).limit(40)
    end
  end
end

app/views/synchronizations/index.html.haml
.home
  .banners
    .container
      - if current_user
        .row
          .col-md-3
            %h3 Synchronization history
          - if current_organization.oauth_uid && is_admin
            .col-md-2
              = link_to "Synchronize", home_synchronize_path, method: :post, class: "btn btn-warning btn-lg"

        - if @synchronizations
          %table.table.table-condensed
            %th Synchronization date
            %th Status
            %th Message

            - @synchronizations.each do |sync|
              - if sync.status == 'ERROR'
                %tr.warning
                  %td= sync.updated_at
                  %td= sync.status
                  %td= sync.message
              - elsif sync.status == 'SUCCESS'
                %tr.success
                  %td= sync.updated_at
                  %td= sync.status
                  %td= sync.message
              - else
                %tr.active
                  %td= sync.updated_at
                  %td= sync.status
                  %td= sync.message
        - else
          .row
            .col-md-12
              %strong No synchronization yet

      - else
        .row.center
          %h3 You need to be logged in to access this page
          = button_to "Go back", home_index_path, method: :get, class: 'btn btn-warning'