config/routes.rb
Rails.application.routes.draw do
  mount Maestrano::Connector::Rails::Engine, at: '/'

  root 'home#index'
  get 'home/index' => 'home#index'
  get 'home/redirect_to_external' => 'home#redirect_to_external'
  get 'home/index' => 'home#index'
  put 'home/update' => 'home#update'
  post 'home/synchronize' => 'home#synchronize'

  get 'synchronizations/index' => 'synchronizations#index'
  get 'shared_entities/index' => 'shared_entities#index'

  match 'auth/:provider/request', to: 'oauth#request_omniauth', via: [:get, :post]
  match 'auth/:provider/callback', to: 'oauth#create_omniauth', via: [:get, :post]
  match 'signout_omniauth', to: 'oauth#destroy_omniauth', as: 'signout_omniauth', via: [:get, :post]

  # Sidekiq Admin
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @organization = current_organization
  end

  def update
    organization = Maestrano::Connector::Rails::Organization.find_by_id(params[:id])

    if organization && is_admin?(current_user, organization)
      old_sync_state = organization.sync_enabled

      organization.synchronized_entities.keys.each do |entity|
        organization.synchronized_entities[entity] = !!params["#{entity}"]
      end
      organization.sync_enabled = organization.synchronized_entities.values.any?

      unless organization.historical_data
        historical_data = !!params['historical-data']
        if historical_data
          organization.date_filtering_limit = nil
          organization.historical_data = true
        else
          organization.date_filtering_limit ||= Time.now
        end
      end
      
      organization.save

      if !old_sync_state && organization.sync_enabled
        Maestrano::Connector::Rails::SynchronizationJob.perform_later(organization, {})
        flash[:info] = 'Congrats, you\'re all set up! Your data are now being synced'
      end
    end

    redirect_to(:back)
  end

  def synchronize
    if is_admin
      Maestrano::Connector::Rails::SynchronizationJob.perform_later(current_organization, (params['opts'] || {}).merge(forced: true))
      flash[:info] = 'Synchronization requested'
    end

    redirect_to(:back)
  end

  def redirect_to_external
    if current_organization && current_organization.instance_url
      redirect_to current_organization.instance_url
    else
      redirect_to 'https://core.futuresimple.com/users/login'
    end
  end

end

app/views/home/index.html.haml
.home
  .banners
    .row
      .col-md-10.col-md-offset-2
        %h2 BaseCRM Connector
        %p
          -if @organization
            Link your company <strong>#{@organization.name} (#{@organization.uid})</strong> to BaseCRM to get your business in synch. Check the status of your connection on this screen.
          -else
            Link your account to BaseCRM to get your business in synch. Check the status of your connection on this screen.

  .container
    - if current_user
      - unless is_admin
        .row
          .col-md-12.alert.alert-warning
            Only administrators can modify the application settings

      .row.link-step{class: "#{@organization.oauth_uid ? 'done' : 'todo'}"}
        .col-md-1.text-center.link-step-number
          %span.badge.link-step-badge
            1
        .col-md-6.link-step-description
          %h
            - if @organization.oauth_uid
              Your BaseCRM account <strong>#{@organization.oauth_name} (#{@organization.oauth_uid})</strong> is currently linked
            - else
              Your BaseCRM account is not linked
        .col-md-2.col-md-offset-3.text-center.link-step-action
          - if @organization.oauth_uid
            = link_to "Disconnect", signout_omniauth_path(organization_id: @organization.id), class: "btn btn-warning btn-lg #{is_admin ? '' : 'disabled'}"
          - else
            = link_to "Link to BaseCRM", "/auth/base/request?org_uid=#{@organization.uid}", class: "btn btn-warning btn-lg" if is_admin

      .spacer1

      .row.link-step{class: "#{(@organization.sync_enabled && @organization.synchronized_entities.values.any?) ? 'done' : 'todo'}"}
        = form_tag home_update_path(id: @organization.id), method: :put do
          .col-md-1.text-center.link-step-number
            %span.badge.link-step-badge
              2
          .col-md-9.link-step-description
            %h
              You can customize which entities are synchronized by the connector:
            .spacer1
            .row
              .col-md-11.col-md-offset-1
                - @organization.synchronized_entities.each do |k, v|
                  .row.sync-entity
                    .col-md-1.link-step-action
                      %input{type: "checkbox", id: "#{k}", name: "#{k}", checked: v}
                    .col-md-6{style: 'padding-top: 5px;'}
                      %label{:for => "#{k}"} #{k.to_s.humanize.pluralize}
                    -if is_admin
                      .col-md-5.text-right
                        - if v && @organization.oauth_uid && @organization.sync_enabled
                          = link_to "Force a synchronization for #{k.to_s.humanize.pluralize} only", home_synchronize_path(opts: {only_entities: [k.to_s]}), method: :post, class: "btn btn-warning btn-sm"
            .spacer1
            .row
              .col-md-4
                %label{:for => 'historical-data'} Synchronize my historical data
              .col-md-2
                %input{type: 'checkbox', id: 'historical-data', name: 'historical-data', checked: @organization.historical_data, onchange: 'historicalDataDisplay();', disabled: @organization.historical_data}
              .col-md-6
                %small#historical-data-display-unchecked{style: "display: #{@organization.historical_data ? 'none' : 'block'}"} Only data created after #{(@organization.date_filtering_limit && @organization.date_filtering_limit.utc || Time.now.utc).to_formatted_s(:long_ordinal)} will be synchronized
                %small#historical-data-display-checked{style: "display: #{!@organization.historical_data ? 'none' : 'block'}"}
                  Synchronizing your historical data will share all data, including the one created prior to #{Time.now.utc} in BaseCRM. This action is <strong>not reversible</strong>. Want to know more? Check 
                  = link_to 'here', 'https://maestrano.atlassian.net/wiki/display/UKB/How+Connec%21+manages+Historical+Data+Sharing'
          .spacer1
          .row
            .col-md-2.col-md-offset-10.text-center.link-step-action
              =submit_tag "#{@organization.sync_enabled ? 'Update' : 'Start synchronizing!'}", class: "btn btn-lg btn-warning #{@organization.oauth_uid ? '' : 'disabled'} text-sm"

      -if @organization.oauth_uid && @organization.sync_enabled
        .spacer2
        .row
          .col-md-4.col-md-offset-4.text-center
            = link_to 'Go to BaseCRM', home_redirect_to_external_path, class: 'btn btn-lg btn-primary'

    - else
      .row
        .col-md-4.col-md-offset-4.center
          = link_to "Link your Maestrano account", Maestrano::Connector::Rails::Engine.routes.url_helpers.default_maestrano_auth_saml_index_path(tenant: :default), class: 'btn btn-warning'