config/routes.rb
Rails.application.routes.draw do
  mount Maestrano::Connector::Rails::Engine, at: '/'

  root 'home#index'
  get 'home/index' => 'home#index'
  get 'home/redirect_to_external' => 'home#redirect_to_external'
  get 'home/index' => 'home#index'
  put 'home/update' => 'home#update'
  post 'home/synchronize' => 'home#synchronize'

  get 'synchronizations/index' => 'synchronizations#index'
  get 'shared_entities/index' => 'shared_entities#index'

  match 'auth/:provider/request', to: 'oauth#request_omniauth', via: [:get, :post]
  match 'auth/:provider/callback', to: 'oauth#create_omniauth', via: [:get, :post]
  match 'signout_omniauth', to: 'oauth#destroy_omniauth', as: 'signout_omniauth', via: [:get, :post]

  # Sidekiq Admin
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BaseCRM Connector
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top.navbar-inverse
      .container-fluid
        .collapse.navbar-collapse#maestrano-navbar-collapse
          %ul.nav.navbar-nav
            = image_tag 'logos/default.png', class: 'logo'

          %ul.nav.navbar-nav
            %li=link_to "Status", root_path

            %li=link_to "History", synchronizations_index_path

            -if is_admin
              %li=link_to "Mapping", shared_entities_index_path

          -if current_user
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a{:href=>"#", :class=>"dropdown-toggle", :'data-toggle'=>"dropdown", :role=>"button"}
                  Hi #{current_user.first_name} #{current_user.last_name}

    .padding-navbar

    .wrapper{style: 'margin-bottom: 15px; '}
      - if flash.any?
        - flash.each do |flash_key, message|
          .alert{:class => "alert-#{flash_key}"}
            %strong= flash.discard(flash_key)

      = yield

    .footer
      .container
        .row
          .col-xs-12
            .copyright
              © Copyright #{Time.now.year}. All rights reserved. Various trademarks held by their respective owners.